version: '3.9'
services:
 pgdatabase:
  image: 'postgres:latest'
  container_name: 'pgdatabase'
  restart: 'always'
  environment:
   POSTGRES_USER: user
   POSTGRES_PASSWORD: user
   POSTGRES_DB: ny_taxi
  ports:
   - 5432:5432
  volumes:
   - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"


 pgadmin:
  image: 'dpage/pgadmin4:latest'
  container_name: 'pgadmin'
  environment:
   PGADMIN_DEFAULT_EMAIL: admin@admin.com
   PGADMIN_DEFAULT_PASSWORD: user
  volumes:
   - "./data_pgadmin:/var/lib/pgadmin"
  ports:
   - 8080:80
  depends_on:
   - pgdatabase


 ingest_database:
  image: 'ingest_database'
  container_name: 'ingestion'
  depends_on:
   - pgdatabase
  restart: always


 jupyter_notebook:
  image: 'jupyter/all-spark-notebook'
  container_name: 'notebook'
  ports :
   - 10000:8888
  volumes:
   - "./notebook:/home/jovyan/work"
  depends_on:
   - pgdatabase
  restart: always
    